### ISSUE TITLE
DEATH,REVIVE, BOOST (Rocketescape),%(attacker) combo% and required-enchants settings

### ISSUE THREAD

**Issue by Frostyeiz** [N3kas/AdvancedEnchantments#185]
"Type" settings:
`DEATH : Runs when player dies due to another player.`
"effect" that can go with DEATH:
```
  REVIVE
         * Dᴇsᴄʀɪᴘᴛɪᴏɴ: Revive player
         * Usᴇᴅ Wɪᴛʜ: DEATH
```

Problem: Basically either DEATH or REVIVE doesn't work, or maybe both, I tested it with this:
```
revival:
  display: '%group-color%Revival'
  description: "A chance to get revived when you die."
  applies-to: 'Helmets'
  type: 'DEATH'
  group: 'LEGENDARY'
  applies:
  - ALL_HELMET
  levels:
    1:
      chance: 100
      effects:
       - 'REVIVE'
```
When I kill a player who has that enchantment, nothing happens, the player just... died.
If this is a bug, please fix it ASAP because the enchantment "Phoenix" needs the type "DEATH" in order to work at what its description said.

%(attacker) combo% var:
Its value always = 1, I tested it with this:
```
  applies-to: 'Weapon'
  type: 'ATTACK'
  group: 'LEGENDARY'
  applies:
  - ALL_AXE
  - ALL_SWORD
  levels:
    1:
      chance: 100
      condition: "%attacker combo% > 5 : %stop%"
      effects:
      - 'MESSAGE:&6%attacker combo% %attacker%'
```
The attacker always get the message "1"

BOOST (effect):
Can you make it temporarily disable fall damage so that the enchantment Rocketescape can work without accidentally make the player who has that enchantment easier to die upon reaching low HP?

required-enchants:
There isn't any problem, but can you make it be more specific, like `required-enchants: lifesteal:4` which mean require a level IV lifesteal instead of just "lifesteal" itself?
