### ISSUE TITLE
Saturation not working

### ISSUE THREAD

**Issue by ShadeyWolf294** [N3kas/AdvancedEnchantments#64]
Hey,

I'm struggling a bit to get the Saturation enchantment to work the way it's inteded to. This is the configuration right now:
```yaml
saturation:
  display: '%group-color%Saturation'
  description: "Passively restores +1 hunger \nevery few seconds"
  applies-to: 'Helmets'
  type: 'EFFECT_STATIC'
  group: 'ELYSIAN'
  applies:
    - ALL_HELMET
  levels:
    1:
      chance: 20
      cooldown: 15
      effects:
        - 'POTION:SATURATION:0:40'
    2:
      chance: 30
      cooldown: 15
      effects:
        - 'POTION:SATURATION:1:60'
    3:
      chance: 40
      cooldown: 15
      effects:
        - 'POTION:SATURATION:2:100'
```
But I noticed that in the explanation for the enchantments.yml document, it says:
```yaml
# You may use POTION:(potion effect):(level):(length in ticks) for ATTACK, DEFENSE, ATTACK_MOB, DEATH, and KILL_MOB
```
However, the EFFECT_STATIC type does not account for this. Hence, it somewhat conflicts with itself and does not work. Any help?

Thanks
